version: '3.8'
services:
  registry-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-registry-service
    restart: always
    ports:
      - 8761:8761
    networks:
      bank_network:
        aliases:
          - app_subnet
        #ipv4_address: 172.20.0.3
networks:
  bank_network:
    name: app_subnet
    external: true